### ISSUE TITLE
requirement update: pyvcf

### ISSUE THREAD

**Issue by lozybean** [rhshah/iCallSV#40]
environment:

* centos6.7
* python3.6

when I install iCallSV with pip:

```
pip install iCallSV
```

it rise a Exception when install dependence `pyvcf==0.6.7` : 

```text
Collecting distribute (from pyvcf==0.6.7->iCallSV)
  Downloading http://mirrors.aliyun.com/pypi/packages/5f/ad/1fde06877a8d7d5c9b60eff7de2d452f639916ae1d48f0b8f97bf97e570a/distribute-0.7.3.zip (145kB)
    100% |████████████████████████████████| 153kB 1.4MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-87v4p3pw/distribute/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/tmp/pip-build-87v4p3pw/distribute/setuptools/extension.py", line 5, in <module>
        from setuptools.dist import _get_unpatched
      File "/tmp/pip-build-87v4p3pw/distribute/setuptools/dist.py", line 7, in <module>
        from setuptools.command.install import install
      File "/tmp/pip-build-87v4p3pw/distribute/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/tmp/pip-build-87v4p3pw/distribute/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/tmp/pip-build-87v4p3pw/distribute/pkg_resources.py", line 1518, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-87v4p3pw/distribute/
```

I can install `pyvcf==0.6.8`  successfully, so would you please udpate the requirement of pyvcf?

**Comment by rhshah** [comment]
My apologies for not making this clear, but the codebase has not been tested on Python 3. Thus I am not sure if its even compatible with that. All the testing has been done on Python 2.7. Thus if you encounter the same issue with Python 2.7 please let me know and we can go from there.

**Comment by lozybean** [comment]
iCallSV seems OK on Python2.7, but when I try to install iAnnotateSV, there comes a error.

```
python setup.py install
```

the last few lines of log:

```
Installed /bio01/software/iCallSV/run_env/lib/python2.7/site-packages/iAnnotateSV-0.0.2-py2.7.egg
Processing dependencies for iAnnotateSV==0.0.2
Searching for PIL
Reading https://pypi.python.org/simple/PIL/
No local packages or working download links found for PIL
error: Could not find suitable distribution for Requirement.parse('PIL')
```

and I can't find `PIL` with `pip`:

```
$ pip install PIL
Collecting PIL
  Could not find a version that satisfies the requirement PIL (from versions: )
No matching distribution found for PIL
```

**Comment by rhshah** [comment]
Thank you for the detailed explanation. 

For I annotate SV you need Pillow, which is called as PIL (https://pypi.python.org/pypi/Pillow/3.4.2)

At some point PIL discontinued and was taken over as Pillow, if you just modify the setup.py, `PIL` with `Pillow` that should work.
